"""Add doctor role, Prescriber.user_id, Prescription.written_by_id/status, PrescriptionLine.quantity_prescribed

Revision ID: 0d35ed6c6192
Revises: c5f41b15a5b6
Create Date: 2026-07-16 12:09:40.482324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d35ed6c6192'
down_revision = 'c5f41b15a5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'Pending'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'Pending'::character varying"))

    # ### end Alembic commands ###
