"""add delivery paperwork fields to batches

Revision ID: 1a6e96057ac8
Revises: 436569b14173
Create Date: 2026-08-14 10:22:31.820440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6e96057ac8'
down_revision = '436569b14173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('d_note_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('lpo_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('delivery_status', sa.String(length=30), nullable=True))
        batch_op.create_foreign_key(None, 'suppliers', ['supplier_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('delivery_status')
        batch_op.drop_column('lpo_number')
        batch_op.drop_column('d_note_number')
        batch_op.drop_column('supplier_id')

    # ### end Alembic commands ###
