"""add quantity_returned and return movement type

Revision ID: 22283f2202ec
Revises: 0d35ed6c6192
Create Date: 2026-07-21 13:00:59.120411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22283f2202ec'
down_revision = '0d35ed6c6192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisition_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_returned', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisition_lines', schema=None) as batch_op:
        batch_op.drop_column('quantity_returned')

    # ### end Alembic commands ###
