"""add lpo_number and delivery_status to delivery line items

Revision ID: 436569b14173
Revises: c1b7547e0c0c
Create Date: 2026-08-13 23:36:14.549399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436569b14173'
down_revision = 'c1b7547e0c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_line_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lpo_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('delivery_status', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_line_items', schema=None) as batch_op:
        batch_op.drop_column('delivery_status')
        batch_op.drop_column('lpo_number')

    # ### end Alembic commands ###
