"""add patient created_at and other pending model changes

Revision ID: 4f59e0068fa2
Revises: 22283f2202ec
Create Date: 2026-07-24 10:11:59.568078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f59e0068fa2'
down_revision = '22283f2202ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
