"""add destination_location to requisitions

Revision ID: 93e956770e2c
Revises: a04e8f6a38c0
Create Date: 2026-07-27 10:12:39.974701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e956770e2c'
down_revision = 'a04e8f6a38c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination_location', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisitions', schema=None) as batch_op:
        batch_op.drop_column('destination_location')

    # ### end Alembic commands ###
