"""add force_logout_at to users

Revision ID: a04e8f6a38c0
Revises: 4f59e0068fa2
Create Date: 2026-07-26 23:14:20.860293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a04e8f6a38c0'
down_revision = '4f59e0068fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('force_logout_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('force_logout_at')

    # ### end Alembic commands ###
