"""add issue_point to requisitions

Revision ID: aabf3bb07376
Revises: 
Create Date: 2026-07-07 14:49:54.087809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aabf3bb07376'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_store', sa.Boolean(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('is_supply_chain')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('sku',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=180),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('reorder_level',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_items_sku'))
        batch_op.create_unique_constraint(None, ['sku'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('quantity_on_hand')
        batch_op.drop_column('unit_of_measure')

    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_ordered', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('quantity_received', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.drop_column('quantity')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.alter_column('po_number',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_purchase_orders_po_number'))
        batch_op.create_unique_constraint(None, ['po_number'])
        batch_op.drop_constraint(batch_op.f('purchase_orders_created_by_id_fkey'), type_='foreignkey')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('requisition_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_required', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('quantity_issued', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.String(length=255), nullable=True))
        batch_op.drop_column('quantity_requested')
        batch_op.drop_column('quantity_fulfilled')

    with op.batch_alter_table('requisitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issue_point', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('approved_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('issued_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('received_by_id', sa.Integer(), nullable=True))
        batch_op.alter_column('req_number',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_requisitions_req_number'))
        batch_op.create_unique_constraint(None, ['req_number'])
        batch_op.drop_constraint(batch_op.f('requisitions_decided_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['issued_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['received_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['approved_by_id'], ['id'])
        batch_op.drop_column('notes')
        batch_op.drop_column('decided_at')
        batch_op.drop_column('decided_by_id')
        batch_op.drop_column('fulfilled_at')

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('from_location', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('to_location', sa.String(length=50), nullable=True))
        batch_op.alter_column('movement_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.alter_column('reference',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'batches', ['batch_id'], ['id'])

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=180),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('contact_person',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('contact_person',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=180),
               existing_nullable=False)

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('reference',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=60),
               existing_nullable=True)
        batch_op.alter_column('movement_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('to_location')
        batch_op.drop_column('from_location')
        batch_op.drop_column('batch_id')

    with op.batch_alter_table('requisitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fulfilled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('decided_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('decided_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('requisitions_decided_by_id_fkey'), 'users', ['decided_by_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_requisitions_req_number'), ['req_number'], unique=True)
        batch_op.alter_column('req_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.drop_column('received_by_id')
        batch_op.drop_column('issued_by_id')
        batch_op.drop_column('approved_by_id')
        batch_op.drop_column('issue_point')

    with op.batch_alter_table('requisition_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_fulfilled', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('quantity_requested', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_column('remarks')
        batch_op.drop_column('quantity_issued')
        batch_op.drop_column('quantity_required')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('purchase_orders_created_by_id_fkey'), 'users', ['created_by_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_purchase_orders_po_number'), ['po_number'], unique=True)
        batch_op.alter_column('po_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_column('quantity_received')
        batch_op.drop_column('quantity_ordered')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_of_measure', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('quantity_on_hand', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_items_sku'), ['sku'], unique=True)
        batch_op.alter_column('reorder_level',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=180),
               existing_nullable=False)
        batch_op.alter_column('sku',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_supply_chain', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('is_store')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
