"""add unit_of_issue to requisition lines

Revision ID: aacfec6ed1dd
Revises: 3015ed6aa598
Create Date: 2026-08-19 11:09:41.013742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aacfec6ed1dd'
down_revision = '3015ed6aa598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisition_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_of_issue', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisition_lines', schema=None) as batch_op:
        batch_op.drop_column('unit_of_issue')

    # ### end Alembic commands ###
