"""Add prescription notes to prescriptions
Revision ID: c1b7547e0c0c
Revises: 93e956770e2c
Create Date: 2026-08-12 10:19:50.472845
"""
from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision = 'c1b7547e0c0c'
down_revision = '93e956770e2c'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_column('notes')
    # ### end Alembic commands ###