"""Add Prescriber model and Prescription.prescriber_id

Revision ID: c5f41b15a5b6
Revises: afb5d86c2b33
Create Date: 2026-07-15 10:29:46.999954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f41b15a5b6'
down_revision = 'afb5d86c2b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prescriber_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'prescribers', ['prescriber_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prescriber_id')

    # ### end Alembic commands ###
